import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CareerPilot",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <>
    <ClerkProvider appearance={{
      baseTheme: dark,
    
    }}>

      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />

            <main className="min-h-screen">{children}</main>
            {/* footer */}
            <footer className="border-t border-border bg-background text-sm text-muted-foreground ">
              <div className="container mx-auto px-4 py-8">
                <p className="text-center text-muted-foreground hover:text-foreground transition-colors duration-300">
                  &copy; {new Date().getFullYear()} made with ❤️ by <Link href="https://github.com/Tarun553">Tarun choudhary</Link>
                </p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
    </>
  )
}

